apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  # Add your base URL here (will be updated by Jenkins or manually)
  # NEXT_PUBLIC_BASE_URL: "http://your-domain.com"

